-- # Class: "Resource" Description: "A generic grouping for any identifiable entity"
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "DataAsset" Description: "A data asset is a resource that contains data, either manually curated, or generated by a computational (ETL) process. Data are raw facts (associations) generated by observations."
--     * Slot: category Description: Monarch asset category. This allows grouping related assets (like data assets) together in sensible categories.
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "Standard" Description: "Standards are agreed-upon conventions or guidelines that ensure uniformity, consistency, and compatibility in various fields and practices. They are like the common languages or rulebooks that different parties use to ensure they understand each other and can work together efficiently. Standards include both exchange standards, like KGX or SSSOM, and ontologies, like HPO or Mondo."
--     * Slot: category Description: Monarch asset category. This allows grouping related assets (like data assets) together in sensible categories.
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "Tool" Description: "A software tool is a computer program designed to help users perform specific tasks or functions, typically making complex or time-consuming processes more efficient and user-friendly. These tasks can range from simple data manipulation to sophisticated design and analysis."
--     * Slot: category Description: Monarch asset category. This allows grouping related assets (like data assets) together in sensible categories.
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "Documentation" Description: "A resource that contains documentation, like a wiki, a webpage with training materials, etc."
--     * Slot: category Description: Monarch asset category. This allows grouping related assets (like data assets) together in sensible categories.
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "ProjectBoard" Description: "A reference to a project board, like a kanban board."
--     * Slot: url Description: A web location
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: Resource_id Description: Autocreated FK slot
--     * Slot: DataAsset_id Description: Autocreated FK slot
--     * Slot: Standard_id Description: Autocreated FK slot
--     * Slot: Tool_id Description: Autocreated FK slot
--     * Slot: Documentation_id Description: Autocreated FK slot
--     * Slot: ProjectBoard_id Description: Autocreated FK slot
--     * Slot: Repository_id Description: Autocreated FK slot
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "Repository" Description: "A reference to a version control repository."
--     * Slot: depends_on Description: A list of packages a resource depends on
--     * Slot: repo_url Description: (str) URL to
--     * Slot: organization Description: 
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "ResourceRegistry" Description: "A registry of different types of data assets"
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: id Description: A unique identifier for a resource
--     * Slot: short_name Description: A short name for a resource
--     * Slot: description Description: A human-readable description for a resource
--     * Slot: documentation Description: A URL to the documentation about this asset.
--     * Slot: monarch_contribution Description: The role the Monarch Initiative plays in the maintainence of this asset.
--     * Slot: repository Description: The repository associated with this resource
--     * Slot: monarch_role Description: The strategic role the asset has for the Monarch core mission.
--     * Slot: citation Description: A citation for the resource
--     * Slot: icon Description: An icon representing the asset.
--     * Slot: icons_url Description: A URL to an icon or set of icon representing the asset. We dont expect this to resolve to a specific icon, more to the place where to get the icons from.
--     * Slot: tagline Description: A short tagline for the resource.
--     * Slot: visual_explainer Description: A visual abstract for the resource.
--     * Slot: url Description: A web location
--     * Slot: website_include Description: Flag if this resource should be shown on the website.
--     * Slot: license Description: A URL to the license.
--     * Slot: contact_id Description: The person responsible for a resources.
-- # Class: "Download" Description: "A downloadable asset, i.e. a data file, an software component, etc."
--     * Slot: id Description: 
--     * Slot: url Description: A web location
--     * Slot: release_status Description: The maturity of the asset, e.g. whether it is under development, or public.
--     * Slot: file_format Description: The format of the file.
-- # Class: "Contact" Description: "The person responsible for a resources."
--     * Slot: id Description: 
--     * Slot: name Description: A human-readable name for a resource
--     * Slot: orcid Description: The ORCID of the contact.
--     * Slot: github Description: The GitHub handle of the contact.
--     * Slot: email Description: The email of the contact.
-- # Class: "Resource_grants" Description: ""
--     * Slot: Resource_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "Resource_see_also" Description: ""
--     * Slot: Resource_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "DataAsset_download" Description: ""
--     * Slot: DataAsset_id Description: Autocreated FK slot
--     * Slot: download_id Description: The web location this asset can be obtained from.
-- # Class: "DataAsset_grants" Description: ""
--     * Slot: DataAsset_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "DataAsset_see_also" Description: ""
--     * Slot: DataAsset_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "Standard_grants" Description: ""
--     * Slot: Standard_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "Standard_see_also" Description: ""
--     * Slot: Standard_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "Tool_grants" Description: ""
--     * Slot: Tool_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "Tool_see_also" Description: ""
--     * Slot: Tool_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "Documentation_grants" Description: ""
--     * Slot: Documentation_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "Documentation_see_also" Description: ""
--     * Slot: Documentation_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "ProjectBoard_grants" Description: ""
--     * Slot: ProjectBoard_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "ProjectBoard_see_also" Description: ""
--     * Slot: ProjectBoard_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "Repository_grants" Description: ""
--     * Slot: Repository_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "Repository_see_also" Description: ""
--     * Slot: Repository_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.
-- # Class: "ResourceRegistry_grants" Description: ""
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: grants Description: The grant used to finance the production of an asset.
-- # Class: "ResourceRegistry_see_also" Description: ""
--     * Slot: ResourceRegistry_id Description: Autocreated FK slot
--     * Slot: see_also Description: A list of related resources.

CREATE TABLE "Download" (
	id INTEGER NOT NULL, 
	url TEXT, 
	release_status VARCHAR(20), 
	file_format VARCHAR(6), 
	PRIMARY KEY (id)
);
CREATE TABLE "Contact" (
	id INTEGER NOT NULL, 
	name TEXT, 
	orcid TEXT, 
	github TEXT, 
	email TEXT, 
	PRIMARY KEY (id)
);
CREATE TABLE "Repository" (
	depends_on TEXT, 
	repo_url TEXT, 
	organization TEXT, 
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(depends_on) REFERENCES "Repository" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "ResourceRegistry" (
	name TEXT, 
	id TEXT NOT NULL, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "Resource" (
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	"ResourceRegistry_id" TEXT, 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "DataAsset" (
	category VARCHAR(27) NOT NULL, 
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	"ResourceRegistry_id" TEXT, 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "Standard" (
	category VARCHAR(17) NOT NULL, 
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	"ResourceRegistry_id" TEXT, 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "Tool" (
	category VARCHAR(20) NOT NULL, 
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	"ResourceRegistry_id" TEXT, 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "Documentation" (
	category VARCHAR(23) NOT NULL, 
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	url TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	"ResourceRegistry_id" TEXT, 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "Repository_grants" (
	"Repository_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("Repository_id", grants), 
	FOREIGN KEY("Repository_id") REFERENCES "Repository" (id)
);
CREATE TABLE "Repository_see_also" (
	"Repository_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("Repository_id", see_also), 
	FOREIGN KEY("Repository_id") REFERENCES "Repository" (id)
);
CREATE TABLE "ResourceRegistry_grants" (
	"ResourceRegistry_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("ResourceRegistry_id", grants), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id)
);
CREATE TABLE "ResourceRegistry_see_also" (
	"ResourceRegistry_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("ResourceRegistry_id", see_also), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id)
);
CREATE TABLE "ProjectBoard" (
	url TEXT, 
	id TEXT NOT NULL, 
	name TEXT, 
	short_name TEXT, 
	description TEXT, 
	documentation TEXT, 
	monarch_contribution VARCHAR(11), 
	repository TEXT, 
	monarch_role VARCHAR(12), 
	citation TEXT, 
	icon TEXT, 
	icons_url TEXT, 
	tagline TEXT, 
	visual_explainer TEXT, 
	website_include BOOLEAN, 
	license VARCHAR(15), 
	"Resource_id" TEXT, 
	"DataAsset_id" TEXT, 
	"Standard_id" TEXT, 
	"Tool_id" TEXT, 
	"Documentation_id" TEXT, 
	"ProjectBoard_id" TEXT, 
	"Repository_id" TEXT, 
	"ResourceRegistry_id" TEXT, 
	contact_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY("Resource_id") REFERENCES "Resource" (id), 
	FOREIGN KEY("DataAsset_id") REFERENCES "DataAsset" (id), 
	FOREIGN KEY("Standard_id") REFERENCES "Standard" (id), 
	FOREIGN KEY("Tool_id") REFERENCES "Tool" (id), 
	FOREIGN KEY("Documentation_id") REFERENCES "Documentation" (id), 
	FOREIGN KEY("ProjectBoard_id") REFERENCES "ProjectBoard" (id), 
	FOREIGN KEY("Repository_id") REFERENCES "Repository" (id), 
	FOREIGN KEY("ResourceRegistry_id") REFERENCES "ResourceRegistry" (id), 
	FOREIGN KEY(contact_id) REFERENCES "Contact" (id)
);
CREATE TABLE "Resource_grants" (
	"Resource_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("Resource_id", grants), 
	FOREIGN KEY("Resource_id") REFERENCES "Resource" (id)
);
CREATE TABLE "Resource_see_also" (
	"Resource_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("Resource_id", see_also), 
	FOREIGN KEY("Resource_id") REFERENCES "Resource" (id)
);
CREATE TABLE "DataAsset_download" (
	"DataAsset_id" TEXT, 
	download_id INTEGER, 
	PRIMARY KEY ("DataAsset_id", download_id), 
	FOREIGN KEY("DataAsset_id") REFERENCES "DataAsset" (id), 
	FOREIGN KEY(download_id) REFERENCES "Download" (id)
);
CREATE TABLE "DataAsset_grants" (
	"DataAsset_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("DataAsset_id", grants), 
	FOREIGN KEY("DataAsset_id") REFERENCES "DataAsset" (id)
);
CREATE TABLE "DataAsset_see_also" (
	"DataAsset_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("DataAsset_id", see_also), 
	FOREIGN KEY("DataAsset_id") REFERENCES "DataAsset" (id)
);
CREATE TABLE "Standard_grants" (
	"Standard_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("Standard_id", grants), 
	FOREIGN KEY("Standard_id") REFERENCES "Standard" (id)
);
CREATE TABLE "Standard_see_also" (
	"Standard_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("Standard_id", see_also), 
	FOREIGN KEY("Standard_id") REFERENCES "Standard" (id)
);
CREATE TABLE "Tool_grants" (
	"Tool_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("Tool_id", grants), 
	FOREIGN KEY("Tool_id") REFERENCES "Tool" (id)
);
CREATE TABLE "Tool_see_also" (
	"Tool_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("Tool_id", see_also), 
	FOREIGN KEY("Tool_id") REFERENCES "Tool" (id)
);
CREATE TABLE "Documentation_grants" (
	"Documentation_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("Documentation_id", grants), 
	FOREIGN KEY("Documentation_id") REFERENCES "Documentation" (id)
);
CREATE TABLE "Documentation_see_also" (
	"Documentation_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("Documentation_id", see_also), 
	FOREIGN KEY("Documentation_id") REFERENCES "Documentation" (id)
);
CREATE TABLE "ProjectBoard_grants" (
	"ProjectBoard_id" TEXT, 
	grants VARCHAR(15), 
	PRIMARY KEY ("ProjectBoard_id", grants), 
	FOREIGN KEY("ProjectBoard_id") REFERENCES "ProjectBoard" (id)
);
CREATE TABLE "ProjectBoard_see_also" (
	"ProjectBoard_id" TEXT, 
	see_also TEXT, 
	PRIMARY KEY ("ProjectBoard_id", see_also), 
	FOREIGN KEY("ProjectBoard_id") REFERENCES "ProjectBoard" (id)
);